#!/usr/bin/env python3
"""Stage 2: HuggingFace Single-Forward Backfill for UMPIRE Hidden States.

Takes candidate responses generated by Stage 1 (vLLM) and performs a fast
teacher-forcing forward pass through the HuggingFace model.
Precisely locates the answer-body's last token via character span mapping,
extracts the last-layer hidden states, and exports [K, hidden_dim] .pt sidecars.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
import time
from pathlib import Path

import torch
from tqdm import tqdm

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from src.datasets import iter_dataset
from src.generation.parser import answer_character_span, parse_structured_response
from src.generation.prompt import build_prompt
from src.generation.runner import _sidecar_filename
from src.models import load_backend


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Backfill UMPIRE answer-last-token hidden states via HF teacher-forcing forward."
    )
    parser.add_argument(
        "--dataset",
        required=True,
        choices=("vilp", "hallusionbench", "mmvet"),
    )
    parser.add_argument("--dataset-source", required=True, type=Path)
    parser.add_argument(
        "--model-family",
        required=True,
        choices=("llava_1_5", "qwen2_5_vl", "internvl3_5"),
    )
    parser.add_argument("--model-path", required=True, type=Path)
    parser.add_argument("--adapter-path", required=True, type=Path)
    parser.add_argument("--samples-input", required=True, type=Path)
    parser.add_argument(
        "--output",
        type=Path,
        help="Optional output path (defaults to updating --samples-input in place atomically).",
    )
    parser.add_argument(
        "--attn-implementation",
        default="sdpa",
        choices=("sdpa", "flash_attention_2", "eager"),
    )
    parser.add_argument("--batch-size", type=int, default=5, help="Batch size for candidate answers forward pass.")
    parser.add_argument("--limit", type=int, help="Optional limit on number of samples to process.")
    return parser.parse_args()


def require_offline_mode() -> None:
    required = ("HF_HUB_OFFLINE", "TRANSFORMERS_OFFLINE", "HF_DATASETS_OFFLINE")
    missing = [name for name in required if os.environ.get(name) != "1"]
    if missing:
        raise RuntimeError(f"offline backfill requires environment variables set to 1: {missing}")


def _build_prompt_text(processor, family: str, question: str, has_image: bool) -> str:
    prompt = build_prompt(question, has_image=has_image, style="xml_lora")
    content = []
    if has_image:
        content.append({"type": "image"})
    content.append({"type": "text", "text": prompt.user})
    messages = [{"role": "user", "content": content}]
    if prompt.system:
        messages.insert(0, {"role": "system", "content": [{"type": "text", "text": prompt.system}]})

    if family == "internvl3_5":
        # InternVL custom conversation formatting
        img_prefix = "<image>\n" if has_image else ""
        sys_prefix = f"{prompt.system}\n\n" if prompt.system else ""
        return f"{img_prefix}{sys_prefix}User: {prompt.user}\nAssistant: "
    elif family == "llava_1_5":
        # LLaVA 1.5 conversation template
        img_prefix = "USER: <image>\n" if has_image else "USER: "
        sys_prefix = f"{prompt.system}\n\n" if prompt.system else ""
        return f"{sys_prefix}{img_prefix}{prompt.user}\nASSISTANT: "
    else:
        # Standard processor chat template (e.g. Qwen2.5-VL)
        return processor.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)


def _find_answer_last_token_index(
    tokenizer,
    prompt_tokens_len: int,
    full_input_ids: list[int],
    raw_response: str,
    response_format: str = "xml",
) -> int:
    """Precisely find the token index in full_input_ids corresponding to the last character of the answer body."""
    try:
        parsed = parse_structured_response(raw_response, response_format)
        if not parsed:
            return len(full_input_ids) - 1
        _, char_end = answer_character_span(raw_response, response_format)
    except Exception:
        return len(full_input_ids) - 1

    gen_token_ids = full_input_ids[prompt_tokens_len:]
    if not gen_token_ids:
        return len(full_input_ids) - 1

    decoded_lengths = [0]
    for end_idx in range(1, len(gen_token_ids) + 1):
        decoded_text = tokenizer.decode(gen_token_ids[:end_idx], skip_special_tokens=False)
        decoded_lengths.append(len(decoded_text))

    token_end_offset = next(
        (idx for idx, length in enumerate(decoded_lengths[1:], start=1) if length >= char_end),
        len(gen_token_ids),
    )
    # 0-indexed token position within the full sequence
    return max(0, min(len(full_input_ids) - 1, prompt_tokens_len + token_end_offset - 1))


def backfill_hidden_states(
    backend,
    dataset_map: dict,
    samples_path: Path,
    output_path: Path,
    *,
    batch_size: int = 5,
    limit: int | None = None,
) -> int:
    backend._load()
    device = backend.device
    model = backend.model
    processor = backend.processor
    tokenizer = getattr(processor, "tokenizer", processor)
    family = backend.family

    # Canonical hidden directory: results/hidden/<model>/<dataset>/
    try:
        relative = samples_path.resolve().relative_to(PROJECT_ROOT / "results" / "generation")
        model_name = relative.parts[0]
        dataset_name = samples_path.stem
        hidden_dir = PROJECT_ROOT / "results" / "hidden" / model_name / dataset_name
    except (ValueError, IndexError):
        hidden_dir = samples_path.parent.with_suffix(".hidden")
    hidden_dir.mkdir(parents=True, exist_ok=True)

    with samples_path.open(encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]

    if not lines:
        print(f"[!] No records in {samples_path}")
        return 0

    header = json.loads(lines[0])
    sample_records = [json.loads(line) for line in lines[1:]]

    # Update header metadata
    header["backfill_manifest"] = {
        "version": "2.0",
        "engine": "huggingface_teacher_forcing",
        "position": "answer_last_token",
        "token_span_alignment": "character_to_token_exact",
        "model_family": family,
        "adapter_path": str(backend.adapter_path) if backend.adapter_path else None,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }

    # Determine subset to process
    unprocessed_indices = []
    for idx, item in enumerate(sample_records):
        sample_id = item["sample"]["sample_id"]
        pt_path = hidden_dir / _sidecar_filename(sample_id)
        if not pt_path.exists() or item.get("hidden_states") is None:
            unprocessed_indices.append(idx)

    if limit is not None and limit > 0:
        target_indices = set(unprocessed_indices[:limit])
    else:
        target_indices = set(unprocessed_indices)

    print(
        f"[*] Total records: {len(sample_records)}, Unprocessed: {len(unprocessed_indices)}, "
        f"Target to process: {len(target_indices)} -> {hidden_dir}",
        flush=True,
    )

    backfilled_count = 0
    start_time = time.time()

    for idx, item in enumerate(tqdm(sample_records, desc="HF Exact Backfill")):
        if idx not in target_indices:
            continue

        sample_id = item["sample"]["sample_id"]
        instance = dataset_map.get(sample_id)
        if instance is None:
            continue

        raw_samples = item.get("samples", [])
        if not raw_samples:
            continue

        pt_path = hidden_dir / _sidecar_filename(sample_id)
        has_image = instance.image is not None
        image = instance.image

        prompt_text = _build_prompt_text(processor, family, instance.question, has_image)
        prompt_token_ids = tokenizer.encode(prompt_text, add_special_tokens=False)
        prompt_len = len(prompt_token_ids)

        candidate_responses = [s.get("raw_response", "") for s in raw_samples]
        hidden_vectors: list[torch.Tensor] = []

        # Process candidate responses in micro-batches
        for b_start in range(0, len(candidate_responses), batch_size):
            b_texts = candidate_responses[b_start : b_start + batch_size]
            full_texts = [f"{prompt_text}{resp}" for resp in b_texts]

            # Prepare multi-modal inputs
            if family == "llava_1_5":
                kwargs = {"text": full_texts, "padding": True, "return_tensors": "pt"}
                if has_image:
                    kwargs["images"] = [image] * len(full_texts)
                inputs = processor(**kwargs).to(device)
            elif family == "qwen2_5_vl":
                kwargs = {"text": full_texts, "padding": True, "return_tensors": "pt"}
                if has_image:
                    kwargs["images"] = [image] * len(full_texts)
                inputs = processor(**kwargs).to(device)
            elif family == "internvl3_5":
                inputs = processor.tokenizer(full_texts, padding=True, return_tensors="pt").to(device)
                if has_image:
                    pixel_values = processor.image_processor(image, return_tensors="pt").pixel_values.to(device)
                    inputs["pixel_values"] = pixel_values.repeat(len(full_texts), 1, 1, 1)
            else:
                raise ValueError(f"unsupported model family: {family}")

            with torch.no_grad():
                outputs = model(**inputs, output_hidden_states=True)
                # Last layer hidden states shape: [batch_size, seq_len, hidden_dim]
                last_hidden_states = outputs.hidden_states[-1]

                for b_idx, resp_text in enumerate(b_texts):
                    row_ids = inputs["input_ids"][b_idx].tolist()
                    # Strip padding tokens if left-padded or right-padded
                    non_pad_ids = [tid for tid in row_ids if tid != tokenizer.pad_token_id]
                    target_token_idx = _find_answer_last_token_index(
                        tokenizer, prompt_len, non_pad_ids, resp_text
                    )
                    # If left-padded, offset target_token_idx by pad count
                    pad_offset = 0
                    if tokenizer.padding_side == "left":
                        pad_offset = len(row_ids) - len(non_pad_ids)
                    exact_idx = min(last_hidden_states.shape[1] - 1, pad_offset + target_token_idx)
                    vec = last_hidden_states[b_idx, exact_idx, :].detach().cpu().to(torch.float16)
                    hidden_vectors.append(vec)

        if hidden_vectors:
            stacked_tensor = torch.stack(hidden_vectors, dim=0)  # Shape: [K, hidden_dim]
            torch.save(stacked_tensor, pt_path)

            try:
                rel_pt_path = str(pt_path.relative_to(PROJECT_ROOT / "results" / "hidden"))
                storage_type = "results_hidden"
            except ValueError:
                rel_pt_path = str(pt_path.relative_to(output_path.parent))
                storage_type = "generation_adjacent"

            item["hidden_states"] = {
                "path": rel_pt_path,
                "storage": storage_type,
                "shape": list(stacked_tensor.shape),
                "dtype": "float16",
                "role": "samples",
                "position": "answer_last_token",
                "source": "hf_teacher_forcing_backfill",
            }
            backfilled_count += 1

    # Atomic write back preserving ALL records
    output_path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        prefix=output_path.name + ".", suffix=".tmp", dir=output_path.parent
    )
    with open(descriptor, "w", encoding="utf-8") as handle:
        handle.write(json.dumps(header, ensure_ascii=False) + "\n")
        for rec in sample_records:
            handle.write(json.dumps(rec, ensure_ascii=False) + "\n")
    Path(temporary).replace(output_path)

    elapsed = time.time() - start_time
    rate = elapsed / max(backfilled_count, 1)
    print(
        f"[+] Successfully backfilled {backfilled_count} samples in {elapsed:.2f}s ({rate:.2f}s/sample)",
        flush=True,
    )
    return backfilled_count


def main() -> None:
    args = parse_args()
    require_offline_mode()
    output_path = args.output or args.samples_input

    dataset_map = {inst.sample_id: inst for inst in iter_dataset(args.dataset, args.dataset_source)}

    backend = load_backend(
        args.model_family,
        args.model_path,
        adapter_path=args.adapter_path,
        engine="huggingface",
        attn_implementation=args.attn_implementation,
    )

    backfill_hidden_states(
        backend,
        dataset_map,
        args.samples_input,
        output_path,
        batch_size=args.batch_size,
        limit=args.limit,
    )


if __name__ == "__main__":
    main()
