#!/usr/bin/env python3
"""Stage 2: HuggingFace Single-Forward Backfill for UMPIRE Hidden States.

Takes candidate responses generated by Stage 1 (vLLM) and performs a fast
single-pass forward through the HuggingFace model with teacher forcing to
extract answer-token hidden states and export [K, hidden_dim] .pt sidecars.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
import time
from pathlib import Path

import torch
from tqdm import tqdm

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from src.datasets import load_dataset_instances
from src.generation.runner import _sidecar_filename
from src.models import load_backend


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Backfill UMPIRE hidden states for vLLM generated samples via HF single-pass forward."
    )
    parser.add_argument(
        "--dataset",
        required=True,
        choices=("vilp", "hallusionbench", "mmvet"),
    )
    parser.add_argument("--dataset-source", required=True, type=Path)
    parser.add_argument(
        "--model-family",
        required=True,
        choices=("llava_1_5", "qwen2_5_vl", "internvl3_5"),
    )
    parser.add_argument("--model-path", required=True, type=Path)
    parser.add_argument("--adapter-path", required=True, type=Path)
    parser.add_argument("--samples-input", required=True, type=Path)
    parser.add_argument(
        "--output",
        type=Path,
        help="Optional output path (defaults to updating --samples-input in place atomically).",
    )
    parser.add_argument("--attn-implementation", default="sdpa", choices=("sdpa", "flash_attention_2", "eager"))
    parser.add_argument("--limit", type=int, help="Optional sample limit for testing.")
    return parser.parse_args()


def require_offline_mode() -> None:
    required = ("HF_HUB_OFFLINE", "TRANSFORMERS_OFFLINE", "HF_DATASETS_OFFLINE")
    missing = [name for name in required if os.environ.get(name) != "1"]
    if missing:
        raise RuntimeError(f"offline backfill requires environment variables set to 1: {missing}")


def _build_full_conversation_text(family: str, system_prompt: str, user_prompt: str, assistant_response: str) -> str:
    if family == "llava_1_5":
        return f"{system_prompt}\n\nUSER: <image>\n{user_prompt}\nASSISTANT: {assistant_response}"
    if family == "qwen2_5_vl":
        return (
            f"<|im_start|>system\n{system_prompt}<|im_end|>\n"
            f"<|im_start|>user\n<|vision_start|><|image_pad|><|vision_end|>{user_prompt}<|im_end|>\n"
            f"<|im_start|>assistant\n{assistant_response}<|im_end|>"
        )
    if family == "internvl3_5":
        return f"<image>\n{system_prompt}\n\nUser: {user_prompt}\nAssistant: {assistant_response}"
    raise ValueError(f"unknown family: {family}")


def backfill_hidden_states(
    backend,
    dataset_instances: dict,
    samples_path: Path,
    output_path: Path,
    *,
    limit: int | None = None,
) -> int:
    backend._load()
    device = backend.device
    model = backend.model
    processor = backend.processor
    family = backend.family

    # Canonical hidden directory: results/hidden/<model>/<dataset>/
    try:
        relative = samples_path.resolve().relative_to(PROJECT_ROOT / "results" / "generation")
        model_name = relative.parts[0]
        dataset_name = samples_path.stem
        hidden_dir = PROJECT_ROOT / "results" / "hidden" / model_name / dataset_name
    except (ValueError, IndexError):
        hidden_dir = samples_path.parent.with_suffix(".hidden")
    hidden_dir.mkdir(parents=True, exist_ok=True)

    with samples_path.open(encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]

    if not lines:
        print(f"[!] No records in {samples_path}")
        return 0

    header = json.loads(lines[0])
    sample_records = [json.loads(line) for line in lines[1:]]

    if limit is not None and limit > 0:
        sample_records = sample_records[:limit]

    print(f"[*] Backfilling hidden states for {len(sample_records)} records into {hidden_dir}...", flush=True)

    updated_records = []
    backfilled_count = 0
    start_time = time.time()

    for item in tqdm(sample_records, desc="HF Forward Backfill"):
        sample_id = item["sample"]["sample_id"]
        instance = dataset_instances.get(sample_id)
        if instance is None:
            updated_records.append(item)
            continue

        raw_samples = item.get("samples", [])
        if not raw_samples:
            updated_records.append(item)
            continue

        pt_filename = _sidecar_filename(sample_id)
        pt_path = hidden_dir / pt_filename

        # Skip if already exists and valid
        if pt_path.exists() and item.get("hidden_states") is not None:
            updated_records.append(item)
            continue

        image = instance.image
        hidden_list: list[torch.Tensor] = []

        system_text = item.get("prompt", {}).get("system", "")
        user_text = item.get("prompt", {}).get("user", "")

        for sample_dict in raw_samples:
            raw_text = sample_dict.get("raw_response", "")
            full_text = _build_full_conversation_text(family, system_text, user_text, raw_text)

            if family == "llava_1_5":
                inputs = processor(text=full_text, images=image, return_tensors="pt").to(device)
            elif family == "qwen2_5_vl":
                inputs = processor(text=[full_text], images=[image], padding=True, return_tensors="pt").to(device)
            elif family == "internvl3_5":
                pixel_values = processor.image_processor(image, return_tensors="pt").pixel_values.to(device)
                inputs = processor.tokenizer(full_text, return_tensors="pt").to(device)
                inputs["pixel_values"] = pixel_values
            else:
                raise ValueError(f"unsupported family: {family}")

            with torch.no_grad():
                outputs = model(**inputs, output_hidden_states=True)
                # Extract hidden state at the last token position
                last_hidden = outputs.hidden_states[-1][0, -1, :].detach().cpu().to(torch.float16)
                hidden_list.append(last_hidden)

        stacked_tensor = torch.stack(hidden_list, dim=0)  # Shape: [K, hidden_dim]
        torch.save(stacked_tensor, pt_path)

        try:
            rel_pt_path = str(pt_path.relative_to(PROJECT_ROOT / "results" / "hidden"))
            storage_type = "results_hidden"
        except ValueError:
            rel_pt_path = str(pt_path.relative_to(output_path.parent))
            storage_type = "generation_adjacent"

        item["hidden_states"] = {
            "path": rel_pt_path,
            "storage": storage_type,
            "shape": list(stacked_tensor.shape),
            "dtype": "float16",
            "role": "samples",
            "position": "answer_last_token",
            "source": "hf_single_forward_backfill",
        }
        updated_records.append(item)
        backfilled_count += 1

    # Atomic write back
    descriptor, temporary = tempfile.mkstemp(
        prefix=output_path.name + ".", suffix=".tmp", dir=output_path.parent
    )
    with open(descriptor, "w", encoding="utf-8") as handle:
        handle.write(json.dumps(header, ensure_ascii=False) + "\n")
        for rec in updated_records:
            handle.write(json.dumps(rec, ensure_ascii=False) + "\n")
    Path(temporary).replace(output_path)

    elapsed = time.time() - start_time
    rate = elapsed / max(backfilled_count, 1)
    print(
        f"[+] Successfully backfilled {backfilled_count} samples in {elapsed:.2f}s ({rate:.2f}s/sample)",
        flush=True,
    )
    return backfilled_count


def main() -> None:
    args = parse_args()
    require_offline_mode()
    output_path = args.output or args.samples_input

    instances = load_dataset_instances(args.dataset, args.dataset_source)
    dataset_map = {inst.sample_id: inst for inst in instances}

    backend = load_backend(
        args.model_family,
        args.model_path,
        adapter_path=args.adapter_path,
        engine="huggingface",
        attn_implementation=args.attn_implementation,
    )

    backfill_hidden_states(
        backend,
        dataset_map,
        args.samples_input,
        output_path,
        limit=args.limit,
    )


if __name__ == "__main__":
    main()
