#!/usr/bin/env python3
"""Stage 2: HuggingFace Single-Forward Backfill for UMPIRE Hidden States.

Takes candidate responses generated by Stage 1 (vLLM) and performs a fast
teacher-forcing forward pass through the HuggingFace model.
Precisely locates the answer-body's last token via character span mapping,
extracts the last-layer hidden states, and exports [K, hidden_dim] .pt sidecars.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
import time
from pathlib import Path

import torch
from tqdm import tqdm

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from src.datasets import iter_dataset
from src.generation.parser import answer_character_span
from src.generation.prompt import build_prompt
from src.generation.runner import _sidecar_filename
from src.models import load_backend


BACKFILL_VERSION = "3.0"
BACKFILL_SOURCE = "hf_teacher_forcing_backfill_v3"
TOKEN_ALIGNMENT = "vllm_generated_token_sidecar"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Backfill UMPIRE answer-last-token hidden states via HF teacher-forcing forward."
    )
    parser.add_argument(
        "--dataset",
        required=True,
        choices=("vilp", "hallusionbench", "mmvet"),
    )
    parser.add_argument("--dataset-source", required=True, type=Path)
    parser.add_argument(
        "--model-family",
        required=True,
        choices=("llava_1_5", "qwen2_5_vl", "internvl3_5"),
    )
    parser.add_argument("--model-path", required=True, type=Path)
    parser.add_argument("--adapter-path", required=True, type=Path)
    parser.add_argument("--samples-input", required=True, type=Path)
    parser.add_argument(
        "--output",
        type=Path,
        help="Optional output path (defaults to updating --samples-input in place atomically).",
    )
    parser.add_argument(
        "--attn-implementation",
        default="sdpa",
        choices=("sdpa", "flash_attention_2", "eager"),
    )
    parser.add_argument("--batch-size", type=int, default=5, help="Batch size for candidate answers forward pass.")
    parser.add_argument("--limit", type=int, help="Optional limit on number of samples to process.")
    return parser.parse_args()


def require_offline_mode() -> None:
    required = ("HF_HUB_OFFLINE", "TRANSFORMERS_OFFLINE", "HF_DATASETS_OFFLINE")
    missing = [name for name in required if os.environ.get(name) != "1"]
    if missing:
        raise RuntimeError(f"offline backfill requires environment variables set to 1: {missing}")


def _build_prompt_text(processor, family: str, question: str, has_image: bool) -> str:
    prompt = build_prompt(question, has_image=has_image, style="xml_lora")
    content = []
    if has_image:
        content.append({"type": "image"})
    content.append({"type": "text", "text": prompt.user})
    messages = [{"role": "user", "content": content}]
    if prompt.system:
        messages.insert(0, {"role": "system", "content": [{"type": "text", "text": prompt.system}]})

    return processor.apply_chat_template(
        messages, add_generation_prompt=True, tokenize=False
    )


def _answer_last_generated_token_offset(
    tokenizer, generated_token_ids: list[int], raw_response: str
) -> int:
    """Return the zero-based generated-token offset containing the answer's final character."""
    _, char_end = answer_character_span(raw_response, "xml")
    if not generated_token_ids:
        raise ValueError("sampled response has no generated token IDs")
    decoded = tokenizer.decode(
        generated_token_ids,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    ).strip()
    if decoded != raw_response.strip():
        raise ValueError("generated token sidecar does not decode to raw_response")
    decoded_lengths = [0]
    for end_idx in range(1, len(generated_token_ids) + 1):
        decoded_text = tokenizer.decode(
            generated_token_ids[:end_idx],
            skip_special_tokens=True,
            clean_up_tokenization_spaces=False,
        ).strip()
        decoded_lengths.append(len(decoded_text))

    token_end_offset = next(
        (idx for idx, length in enumerate(decoded_lengths[1:], start=1) if length >= char_end),
        None,
    )
    if token_end_offset is None:
        raise ValueError("answer character span does not align to generated token IDs")
    return token_end_offset - 1


def _load_generated_token_ids(samples_path: Path, item: dict) -> list[list[int]]:
    descriptor = item.get("generation_tokens")
    if not isinstance(descriptor, dict) or not isinstance(descriptor.get("path"), str):
        raise ValueError("sample record lacks generation_tokens descriptor")
    root = samples_path.parent.resolve()
    token_path = (root / descriptor["path"]).resolve()
    if not token_path.is_relative_to(root):
        raise ValueError("generation token path escapes samples directory")
    payload = torch.load(token_path, map_location="cpu", weights_only=True)
    if not isinstance(payload, dict):
        raise ValueError(f"invalid generation token sidecar: {token_path}")
    values: list[list[int]] = []
    for index in range(len(item.get("samples", []))):
        tensor = payload.get(f"sample_{index}")
        if not isinstance(tensor, torch.Tensor) or tensor.ndim != 1:
            raise ValueError(f"invalid sample_{index} token IDs in {token_path}")
        values.append([int(value) for value in tensor.tolist()])
    return values


def _current_sidecar(item: dict, path: Path, expected_rows: int) -> bool:
    descriptor = item.get("hidden_states")
    if not isinstance(descriptor, dict):
        return False
    if descriptor.get("source") != BACKFILL_SOURCE or not path.is_file():
        return False
    try:
        tensor = torch.load(path, map_location="cpu", weights_only=True)
    except (OSError, RuntimeError, ValueError):
        return False
    return (
        isinstance(tensor, torch.Tensor)
        and tensor.ndim == 2
        and tensor.shape[0] == expected_rows
        and list(tensor.shape) == descriptor.get("shape")
    )


def _atomic_torch_save(tensor: torch.Tensor, path: Path) -> None:
    descriptor, temporary = tempfile.mkstemp(
        prefix=path.name + ".", suffix=".tmp", dir=path.parent
    )
    os.close(descriptor)
    try:
        torch.save(tensor, temporary)
        os.replace(temporary, path)
    except BaseException:
        if os.path.exists(temporary):
            os.unlink(temporary)
        raise


def _answer_hidden_index(
    sequence_length: int,
    right_padding: int,
    generated_token_count: int,
    answer_offset: int,
) -> int:
    index = sequence_length - right_padding - generated_token_count + answer_offset
    if not 0 <= index < sequence_length:
        raise ValueError("answer token index exceeds model hidden-state sequence")
    return index


def backfill_hidden_states(
    backend,
    dataset_map: dict,
    samples_path: Path,
    output_path: Path,
    *,
    batch_size: int = 5,
    limit: int | None = None,
) -> int:
    backend._load()
    device = backend.device
    model = backend.model
    processor = backend.processor
    tokenizer = getattr(processor, "tokenizer", processor)
    family = backend.family

    # Canonical hidden directory: results/hidden/<model>/<dataset>/
    try:
        relative = samples_path.resolve().relative_to(PROJECT_ROOT / "results" / "generation")
        model_name = relative.parts[0]
        dataset_name = samples_path.stem
        hidden_dir = PROJECT_ROOT / "results" / "hidden" / model_name / dataset_name
    except (ValueError, IndexError):
        hidden_dir = samples_path.parent.with_suffix(".hidden")
    hidden_dir.mkdir(parents=True, exist_ok=True)

    with samples_path.open(encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]

    if not lines:
        print(f"[!] No records in {samples_path}")
        return 0

    header = json.loads(lines[0])
    sample_records = [json.loads(line) for line in lines[1:]]

    if header.get("record_type") != "run" or not isinstance(header.get("run"), dict):
        raise ValueError(f"samples input lacks a valid run header: {samples_path}")
    run = header["run"]
    if run.get("dataset") is None or run.get("model_family") != family:
        raise ValueError("samples input does not match requested model family")
    if run.get("model_runtime", {}).get("engine") != "vllm":
        raise ValueError("hidden-state backfill requires vLLM generation input")

    # This deterministic top-level manifest is merged into the UQ run identity.
    header["backfill_manifest"] = {
        "version": BACKFILL_VERSION,
        "engine": "huggingface_teacher_forcing",
        "position": "answer_last_token",
        "token_span_alignment": TOKEN_ALIGNMENT,
        "model_family": family,
        "adapter_path": str(backend.adapter_path) if backend.adapter_path else None,
        "prompt_sha256": run.get("prompt_sha256"),
    }

    # Only valid XML records participate in UQ; invalid records remain preserved
    # without a misleading answer-last-token descriptor.
    unprocessed_indices = []
    for idx, item in enumerate(sample_records):
        sample_id = item["sample"]["sample_id"]
        raw_samples = item.get("samples", [])
        if not raw_samples or not all(
            sample.get("sections_valid") is True for sample in raw_samples
        ):
            continue
        pt_path = hidden_dir / _sidecar_filename(sample_id)
        if not _current_sidecar(item, pt_path, len(raw_samples)):
            unprocessed_indices.append(idx)

    if limit is not None and limit > 0:
        target_indices = set(unprocessed_indices[:limit])
    else:
        target_indices = set(unprocessed_indices)

    print(
        f"[*] Total records: {len(sample_records)}, Unprocessed: {len(unprocessed_indices)}, "
        f"Target to process: {len(target_indices)} -> {hidden_dir}",
        flush=True,
    )

    backfilled_count = 0
    start_time = time.time()

    for idx, item in enumerate(tqdm(sample_records, desc="HF Exact Backfill")):
        if idx not in target_indices:
            continue

        sample_id = item["sample"]["sample_id"]
        instance = dataset_map.get(sample_id)
        if instance is None:
            raise ValueError(f"dataset source lacks generated sample_id: {sample_id}")

        raw_samples = item.get("samples", [])
        if not raw_samples:
            continue

        pt_path = hidden_dir / _sidecar_filename(sample_id)
        has_image = instance.image is not None
        image = instance.image

        prompt_text = _build_prompt_text(processor, family, instance.question, has_image)
        candidate_responses = [s.get("raw_response", "") for s in raw_samples]
        generated_token_ids = _load_generated_token_ids(samples_path, item)
        hidden_vectors: list[torch.Tensor] = []

        # Process candidate responses in micro-batches
        for b_start in range(0, len(candidate_responses), batch_size):
            b_texts = candidate_responses[b_start : b_start + batch_size]
            b_token_ids = generated_token_ids[b_start : b_start + batch_size]
            prompt_texts = [prompt_text] * len(b_texts)

            # Build the multimodal prompt once per row, then append the exact
            # vLLM token IDs. This avoids tokenizer/processor length drift.
            if family == "llava_1_5":
                kwargs = {"text": prompt_texts, "padding": True, "return_tensors": "pt"}
                if has_image:
                    kwargs["images"] = [image] * len(prompt_texts)
                inputs = processor(**kwargs).to(device)
            elif family == "qwen2_5_vl":
                kwargs = {"text": prompt_texts, "padding": True, "return_tensors": "pt"}
                if has_image:
                    kwargs["images"] = [image] * len(prompt_texts)
                inputs = processor(**kwargs).to(device)
            elif family == "internvl3_5":
                inputs = processor.tokenizer(prompt_texts, padding=True, return_tensors="pt").to(device)
                if has_image:
                    pixel_values = processor.image_processor(image, return_tensors="pt").pixel_values.to(device)
                    inputs["pixel_values"] = pixel_values.repeat(len(prompt_texts), 1, 1, 1)
            else:
                raise ValueError(f"unsupported model family: {family}")

            prompt_rows: list[list[int]] = []
            prompt_type_rows: dict[str, list[list[int]]] = {}
            for row_index in range(len(b_texts)):
                mask = inputs["attention_mask"][row_index].bool()
                prompt_rows.append(
                    [int(value) for value in inputs["input_ids"][row_index][mask].tolist()]
                )
                for key in ("mm_token_type_ids", "input_token_type_ids", "token_type_ids"):
                    if key in inputs:
                        prompt_type_rows.setdefault(key, []).append(
                            [int(value) for value in inputs[key][row_index][mask].tolist()]
                        )
            full_rows = [
                prompt_ids + response_ids
                for prompt_ids, response_ids in zip(prompt_rows, b_token_ids, strict=True)
            ]
            pad_id = tokenizer.pad_token_id
            if pad_id is None:
                raise ValueError("tokenizer requires pad_token_id for batched backfill")
            max_length = max(len(row) for row in full_rows)
            padded_rows: list[list[int]] = []
            attention_rows: list[list[int]] = []
            left_offsets: list[int] = []
            right_offsets: list[int] = []
            for row in full_rows:
                padding = max_length - len(row)
                left_padding = padding if tokenizer.padding_side == "left" else 0
                right_padding = padding - left_padding
                padded_rows.append([pad_id] * left_padding + row + [pad_id] * right_padding)
                attention_rows.append([0] * left_padding + [1] * len(row) + [0] * right_padding)
                left_offsets.append(left_padding)
                right_offsets.append(right_padding)
            inputs["input_ids"] = torch.tensor(
                padded_rows, dtype=torch.long, device=device
            )
            inputs["attention_mask"] = torch.tensor(
                attention_rows, dtype=torch.long, device=device
            )
            inputs.pop("position_ids", None)
            for key in ("mm_token_type_ids", "input_token_type_ids", "token_type_ids"):
                if key not in inputs:
                    continue
                values = torch.zeros_like(inputs["input_ids"])
                for row_index, prompt_types in enumerate(prompt_type_rows[key]):
                    start = left_offsets[row_index]
                    values[row_index, start : start + len(prompt_types)] = torch.tensor(
                        prompt_types, dtype=values.dtype, device=device
                    )
                inputs[key] = values

            with torch.no_grad():
                outputs = model(**inputs, output_hidden_states=True)
                # Last layer hidden states shape: [batch_size, seq_len, hidden_dim]
                last_hidden_states = outputs.hidden_states[-1]

                for b_idx, (resp_text, response_ids) in enumerate(
                    zip(b_texts, b_token_ids, strict=True)
                ):
                    answer_offset = _answer_last_generated_token_offset(
                        tokenizer, response_ids, resp_text
                    )
                    # Index from the sequence end so image-token expansion in
                    # the prompt cannot shift the generated-token position.
                    exact_idx = _answer_hidden_index(
                        last_hidden_states.shape[1],
                        right_offsets[b_idx],
                        len(response_ids),
                        answer_offset,
                    )
                    vec = last_hidden_states[b_idx, exact_idx, :].detach().cpu().to(torch.float16)
                    hidden_vectors.append(vec)

        if hidden_vectors:
            stacked_tensor = torch.stack(hidden_vectors, dim=0)  # Shape: [K, hidden_dim]
            _atomic_torch_save(stacked_tensor, pt_path)

            try:
                rel_pt_path = str(pt_path.relative_to(PROJECT_ROOT / "results" / "hidden"))
                storage_type = "results_hidden"
            except ValueError:
                rel_pt_path = str(pt_path.relative_to(output_path.parent))
                storage_type = "generation_adjacent"

            item["hidden_states"] = {
                "path": rel_pt_path,
                "storage": storage_type,
                "shape": list(stacked_tensor.shape),
                "dtype": "float16",
                "role": "samples",
                "position": "answer_last_token",
                "source": BACKFILL_SOURCE,
                "version": BACKFILL_VERSION,
                "token_alignment": TOKEN_ALIGNMENT,
            }
            backfilled_count += 1

    incomplete = []
    for idx, item in enumerate(sample_records):
        if limit is not None and limit > 0 and idx not in target_indices:
            continue
        raw_samples = item.get("samples", [])
        if not raw_samples or not all(
            sample.get("sections_valid") is True for sample in raw_samples
        ):
            continue
        sample_id = item["sample"]["sample_id"]
        pt_path = hidden_dir / _sidecar_filename(sample_id)
        if not _current_sidecar(item, pt_path, len(raw_samples)):
            incomplete.append(sample_id)
    if incomplete:
        preview = ", ".join(incomplete[:5])
        raise RuntimeError(
            f"backfill incomplete for {len(incomplete)} valid records: {preview}"
        )

    # Atomic write back preserving ALL records
    output_path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        prefix=output_path.name + ".", suffix=".tmp", dir=output_path.parent
    )
    with open(descriptor, "w", encoding="utf-8") as handle:
        handle.write(json.dumps(header, ensure_ascii=False) + "\n")
        for rec in sample_records:
            handle.write(json.dumps(rec, ensure_ascii=False) + "\n")
    Path(temporary).replace(output_path)

    elapsed = time.time() - start_time
    rate = elapsed / max(backfilled_count, 1)
    print(
        f"[+] Successfully backfilled {backfilled_count} samples in {elapsed:.2f}s ({rate:.2f}s/sample)",
        flush=True,
    )
    return backfilled_count


def main() -> None:
    args = parse_args()
    require_offline_mode()
    output_path = args.output or args.samples_input

    dataset_map = {inst.sample_id: inst for inst in iter_dataset(args.dataset, args.dataset_source)}

    backend = load_backend(
        args.model_family,
        args.model_path,
        adapter_path=args.adapter_path,
        engine="huggingface",
        attn_implementation=args.attn_implementation,
    )

    backfill_hidden_states(
        backend,
        dataset_map,
        args.samples_input,
        output_path,
        batch_size=args.batch_size,
        limit=args.limit,
    )


if __name__ == "__main__":
    main()
