"""Backward-compatible wrapper re-exporting from ERA (Early Rationale Attribution)."""
from src.improvement.era import (
    DESTS,
    DIRECT_LAYERS,
    EPS,
    FEATURES,
    GROUPS,
    EcaResult,
    EraResult,
    _EcaAccumulator,
    _EraAccumulator,
    _get_decoder_layers,
    _make_chunked_eager,
    _repeat_kv,
    compute_eca,
    compute_era,
    layer_features,
)

__all__ = [
    "DESTS",
    "DIRECT_LAYERS",
    "EPS",
    "FEATURES",
    "GROUPS",
    "EcaResult",
    "EraResult",
    "_EcaAccumulator",
    "_EraAccumulator",
    "_get_decoder_layers",
    "_make_chunked_eager",
    "_repeat_kv",
    "compute_eca",
    "compute_era",
    "layer_features",
]
